<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <UserSecretsId>20d46c71-4679-4b99-a96f-13babee90ed6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\bak\**" />
    <Compile Remove="Pages\Shared\bak\**" />
    <Content Remove="Pages\bak\**" />
    <Content Remove="Pages\Shared\bak\**" />
    <EmbeddedResource Remove="Pages\bak\**" />
    <EmbeddedResource Remove="Pages\Shared\bak\**" />
    <None Remove="Pages\bak\**" />
    <None Remove="Pages\Shared\bak\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Pages\AddProducts.cshtml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Pages\AddProducts.cshtml" />
    <Content Remove="wwwroot\js\Index.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="microsoft-web-helpers" Version="2.1.20710.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Stripe.net" Version="48.1.0" />
  </ItemGroup>
</Project>
